### PR TITLE
Adds spotify back in.

### PR DESCRIPTION
**Pull request by ppanthony**
From what I can tell looks like this is no longer false positiving. If there's any further detail on accounts which are exhibiting false positive behaviour happy to look at this.

### CODE REVIEW

**Comment by C3n7ral051nt4g3ncy** [comment]
@ppanthony Good one! ! 🚀

**Review by C3n7ral051nt4g3ncy — CHANGES_REQUESTED** [review]
@ppanthony : There should be at least 2 known accounts.

**Comment by C3n7ral051nt4g3ncy** [comment]
@ppanthony: Noticed Spotify is already in the` wmn-data.json`

**Comment by WebBreacher** [comment]
Yes. Thank you @C3n7ral051nt4g3ncy for noticing. We have an automated checker that should have caught this too. I will research that. @ppanthony it looks like since we are already checking spotify and the URL is the same as your's, this PR may not be necessary. Are you finding the existing Spotify entry not sufficient?

**Comment by ppanthony** [comment]
@WebBreacher @C3n7ral051nt4g3ncy - my bad. Didn't notice that it was in there, was just looking to contribute to the project and noticed the previous 'removed' discussion here: https://github.com/WebBreacher/WhatsMyName/wiki/Problem-Removed-Sites of which spotify was listed. You can close the pull! Sorry again!

**Pull request closed without merging**
