### PR TITLE
Add slack

### PR DESCRIPTION
**Pull request by Sector035**

### CODE REVIEW

**Comment by bcoles** [comment]
Hey @Sector035 it looks like your branches are messed up. The changes in each PR are being dragged into the next.

To avoid this, make sure you're branching from `master`.

```
git checkout master # <-- super important
git checkout -b slack
vi web_accounts_list.json # makes some changes to add web_accounts_list.json
git add web_accounts_list.json
git commit -m "Add slack"
git push origin slack
git checkout master
```

**Comment by Sector035** [comment]
Thx! At the moment I read the first line I knew what was wrong already
-sigh- Understandable that this is not gonna work. Best way forward? Merge
branches and create one new PR? Or is there a different 'easy' fix?

**Comment by bcoles** [comment]
> 
> Thx! At the moment I read the first line I knew what was wrong already -sigh- Understandable that this is not gonna work. Best way forward? Merge branches and create one new PR? Or is there a different 'easy' fix?
> […](#)

That would be @WebBreacher 's call, as WebBreacher has to merge them.

My advice would be to make one branch and one PR for each new addition. This is best practice and makes merging *much* easier, and helps limit merge conflicts.

This is also super useful in the event that there's a disagreement over one of the changes, as the other changes can be merged in cleanly without holding up the PR.

This also allows the repository owner to test and merge the changes at their leisure, rather than having to do it all in one go, increasing the speed with which changes are merged.

The longer a PR stays open without being merged, the more likely it is going to cause merge conflicts, making merging more difficult.

**Comment by WebBreacher** [comment]
Thanks for participating @bcoles and @Sector035 . I agree with @bcoles here... @Sector035 , would you mind "...make one branch and one PR for each new addition. This is best practice and makes merging much easier, and helps limit merge conflicts."

**Comment by Sector035** [comment]
Thanks for the feedback guys! I will be off for a bit, so I'll probably
resubmit everything in about 2,5 weeks time.

**Pull request closed without merging**
