### PR TITLE
Update web_accounts_list.json

### PR DESCRIPTION
**Pull request by BerndDasByte**
Fixed platform slideshare (changed account_existence_string)

### CODE REVIEW

**Comment by WebBreacher** [comment]
While this detection string works for the `test` account, it does not for others (https://www.slideshare.net/john). Can you please re-examine your detection string and make it work for a broader set of accounts?

**Comment by BerndDasByte** [comment]
Could you recheck that? I tested the detection string for the accounts `john`, `master`, `goku` and `dragon` and found them all.

**Comment by BerndDasByte** [comment]
Have you checked it multiple times? Sometimes there are False Negatives, why ever ...

**Comment by WebBreacher** [comment]
Yes! Apologies for the delay. rechecked on several accounts and it works just fine like you said. THANKS for the submission!

**Pull request merged**
