### PR TITLE
Adding 1 website

### PR DESCRIPTION
**Pull request by C3n7ral051nt4g3ncy**
- Added `1 Website`
- Category: `Gaming`
- Name: Diablo2
- Example: https://diablo2.io/member/John/

### CODE REVIEW

**Comment by WebBreacher** [comment]
You have accidentally been submitting the `.DS_Store` from your computer with your submissions. I just added that file to the project's `.gitignore` list so it doesn't get added.

Because of this, this PR needs to probably be modified or cancelled and resubmitted since you are submitting that ignored file.

**Comment by C3n7ral051nt4g3ncy** [comment]
> You have accidentally been submitting the `.DS_Store` from your computer with your submissions. I just added that file to the project's `.gitignore` list so it doesn't get added.
> 
> Because of this, this PR needs to probably be modified or cancelled and resubmitted since you are submitting that ignored file.

It's GitHub Desktop that is automatically pushing the `.DS_Store` with the submission for some reason.

**Comment by C3n7ral051nt4g3ncy** [comment]
@WebBreacher : I have now deleted` .DS_Store` from my repository

**Comment by WebBreacher** [comment]
Added. Thank you.

**Pull request merged**
