### PR TITLE
Use Duolingo's api directly

### PR DESCRIPTION
**Pull request by ef1500**
There was a small false negative error when trying to enumerate a duolingo account because it takes a few seconds for the webpage to load. This Takes Care of it.

### CODE REVIEW

**Comment by WebBreacher** [comment]
Thanks for catching this and for taking the time to research and make this PR. Could you make 1 change please? Create the `pretty_uri` parameter with a value of `"https://www.duolingo.com/profile/{account}"`. Some of the downstream apps that use WhatsMyName check for the acct using the `check_uri` and then display the results using the `pretty_uri`.

**Comment by WebBreacher** [comment]
Here is an example from the Gab entry:
```
        "name" : "Gab",
        "check_uri" : "https://gab.com/api/v1/account_by_username/{account}",
        "pretty_uri" : "https://gab.com/{account}",
```

**Comment by ef1500** [comment]
Sure thing. Should be good to go now!

**Comment by WebBreacher** [comment]
Thanks!

**Pull request merged**
